# Generated by Django 4.0.4 on 2022-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
