# Generated by Django 4.0.4 on 2022-04-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regauth',
            name='phone',
        ),
    ]
